version: "3.9"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    volumes:
      - app_data:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data:
  app_data: